# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: run-circleci-artifacts-redirector
      # You may pin to the exact commit or the version.
      # uses: larsoner/circleci-artifacts-redirector-action@f21583e2add81332abb27786e888ad1665087032
      uses: larsoner/circleci-artifacts-redirector-action@0.2.0
      with:
        # The GITHUB_TOKEN secret
        repo-token: 2747a455d7e2695479491adcc03f23bc5d0df02b
        # Path to the CircleCI artifact
        artifact-path: target/my-app-1.0-SNAPSHOT.jar

